apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: aw0hj39bv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aw0hj39bv-nodejs 
  name: aw0hj39bv-nodejs
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: aw0hj39bv-nodejs
    weight: 100 
